name: x_clone
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cloud_firestore: ^5.5.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.7.0
  equatable: ^2.0.7
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_secure_storage: ^9.2.2
  freezed_annotation: ^2.4.4
  get_it: ^8.0.2
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  hydrated_bloc: ^9.1.5
  json_annotation: ^4.9.0
  logger: ^2.5.0
  path_provider: ^2.1.5
  responsive_framework: ^1.5.1
  shared_preferences: ^2.3.3
  loading_animation_widget: ^1.3.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
  # assets:
  # - assets/
  # - assets/images/
